spring.application.name=spaceroom

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.rlaxuhyafxlukwbhgkjd
spring.datasource.password=Cmdspace973798

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true